version: '2'
output: 'prefixed'

includes:
  _: https://raw.githubusercontent.com/FasterArbeit/task/master/go.yml

vars:
  REPOSITORY_NAME: 'stellar'
  PATH: 'github.com/RaphaelPour/stellar'

tasks:
  test:
    desc: Run go test unittests
    cmds:
      - mkdir -p coverage
      - go test -run "^Test[^_]" -v ./... -coverprofile=coverage/unittest_coverage.out -covermode=atomic
  coverage:
    desc: Generate coverage report
    cmds:
      - |
        echo "mode: atomic" > coverage/total
        grep "^github.com" -h coverage/*.out | sort >> coverage/total
        go tool cover -html=coverage/total -o coverage/coverage.html

